"""
Curated list of popular songs used in TikTok sport edits.
Serves as a baseline to ensure the dashboard always has 200+ songs.
"""

SEED_SONGS = [
    # Phonk / Edit classics
    {"title": "CLOSE EYES", "artist": "DVRST"},
    {"title": "METAMORPHOSIS", "artist": "INTERWORLD"},
    {"title": "MURDER IN MY MIND", "artist": "Kordhell"},
    {"title": "LIVE ANOTHER DAY", "artist": "Kordhell"},
    {"title": "Land of Fire", "artist": "Kordhell"},
    {"title": "DEMONSLAYER", "artist": "Kordhell"},
    {"title": "MOONLIGHT", "artist": "Kordhell"},
    {"title": "Murder Plot", "artist": "Kordhell"},
    {"title": "Neon Blade", "artist": "MoonDeity"},
    {"title": "OVERRIDE", "artist": "KSLV Noh"},
    {"title": "RAVE", "artist": "Dxrk"},
    {"title": "RAVE", "artist": "INTERWORLD"},
    {"title": "GigaChad Theme", "artist": "g3ox_em"},
    {"title": "MONTAGEM SLOWED", "artist": "DJ Brunin XM"},
    {"title": "MONTAGEM CORAL", "artist": "DJ VP"},
    {"title": "Funk of Galactico", "artist": "Mc Rick"},
    {"title": "Spell", "artist": "Nxwledge"},
    {"title": "WAKE UP!", "artist": "moonlight"},
    {"title": "SLAY!", "artist": "Eternxlkz"},
    {"title": "MANIAC", "artist": "Flashback"},
    {"title": "GHOSTFACE PLAYA", "artist": "PHONK"},
    {"title": "Memory Reboot", "artist": "VØJ & Narvent"},
    {"title": "Sleepwalker", "artist": "Akiaura"},
    {"title": "Nightcall", "artist": "Kavinsky"},
    {"title": "BACKGROUND", "artist": "Lxaes"},
    {"title": "SAHARA", "artist": "Hensonn"},
    {"title": "SPIT IN MY FACE", "artist": "ThxSoMch"},
    {"title": "Ecstasy", "artist": "SUICIDAL-IDOL"},
    {"title": "To The Moon", "artist": "Jnr Choi"},
    {"title": "NEXT!", "artist": "Playboi Carti"},
    {"title": "MIDDLE OF THE NIGHT", "artist": "Elley Duhé"},
    {"title": "Cradles", "artist": "Sub Urban"},
    {"title": "Way Down We Go", "artist": "Kaleo"},
    {"title": "Sweater Weather", "artist": "The Neighbourhood"},
    {"title": "Do I Wanna Know?", "artist": "Arctic Monkeys"},
    {"title": "Runaway", "artist": "Aurora"},
    {"title": "HUMBLE", "artist": "Kendrick Lamar"},
    {"title": "Seven Nation Army", "artist": "The White Stripes"},
    {"title": "Dancin", "artist": "Aaron Smith"},
    # Pop / mainstream
    {"title": "AFTER DARK", "artist": "Mr.Kitty"},
    {"title": "The Perfect Girl", "artist": "Mareux"},
    {"title": "Die For You", "artist": "The Weeknd"},
    {"title": "Blinding Lights", "artist": "The Weeknd"},
    {"title": "Starboy", "artist": "The Weeknd"},
    {"title": "Save Your Tears", "artist": "The Weeknd"},
    {"title": "The Hills", "artist": "The Weeknd"},
    {"title": "Popular", "artist": "The Weeknd"},
    {"title": "Creepin'", "artist": "Metro Boomin"},
    {"title": "Too Many Nights", "artist": "Metro Boomin"},
    {"title": "Superhero", "artist": "Metro Boomin"},
    {"title": "One Dance", "artist": "Drake"},
    {"title": "GODS", "artist": "NewJeans"},
    {"title": "Heather", "artist": "Conan Gray"},
    {"title": "Industry Baby", "artist": "Lil Nas X"},
    {"title": "Let Me Down Slowly", "artist": "Alec Benjamin"},
    {"title": "Lovely", "artist": "Billie Eilish"},
    {"title": "Levitating", "artist": "Dua Lipa"},
    {"title": "Believer", "artist": "Imagine Dragons"},
    {"title": "Rockstar", "artist": "Post Malone"},
    {"title": "Bloody Mary", "artist": "Lady Gaga"},
    {"title": "Empire State of Mind", "artist": "JAY-Z"},
    {"title": "On Top of the World", "artist": "Imagine Dragons"},
    {"title": "Rather Be", "artist": "Clean Bandit"},
    {"title": "See You Again", "artist": "Wiz Khalifa"},
    {"title": "Stressed Out", "artist": "Twenty One Pilots"},
    {"title": "Until I Found You", "artist": "Stephen Sanchez"},
    {"title": "Ghost", "artist": "Justin Bieber"},
    {"title": "Heat Waves", "artist": "Glass Animals"},
    {"title": "I Really Want to Stay at Your House", "artist": "Rosa Walton"},
    {"title": "Alone", "artist": "Marshmello"},
    {"title": "Snowfall", "artist": "Øneheart"},
    # More sport edit bangers
    {"title": "INDUSTRY BABY", "artist": "Lil Nas X"},
    {"title": "Money Trees", "artist": "Kendrick Lamar"},
    {"title": "m.A.A.d city", "artist": "Kendrick Lamar"},
    {"title": "DNA", "artist": "Kendrick Lamar"},
    {"title": "Not Like Us", "artist": "Kendrick Lamar"},
    {"title": "Sicko Mode", "artist": "Travis Scott"},
    {"title": "HIGHEST IN THE ROOM", "artist": "Travis Scott"},
    {"title": "goosebumps", "artist": "Travis Scott"},
    {"title": "FE!N", "artist": "Travis Scott"},
    {"title": "90210", "artist": "Travis Scott"},
    {"title": "Mask Off", "artist": "Future"},
    {"title": "March Madness", "artist": "Future"},
    {"title": "Low Life", "artist": "Future"},
    {"title": "XO Tour Llif3", "artist": "Lil Uzi Vert"},
    {"title": "Just Wanna Rock", "artist": "Lil Uzi Vert"},
    {"title": "Pink Tape", "artist": "Lil Uzi Vert"},
    {"title": "All Girls Are The Same", "artist": "Juice WRLD"},
    {"title": "Lucid Dreams", "artist": "Juice WRLD"},
    {"title": "Robbery", "artist": "Juice WRLD"},
    {"title": "Legends", "artist": "Juice WRLD"},
    {"title": "Wasted", "artist": "Juice WRLD"},
    {"title": "Black & White", "artist": "Juice WRLD"},
    {"title": "Dior", "artist": "Pop Smoke"},
    {"title": "For The Night", "artist": "Pop Smoke"},
    {"title": "What You Know Bout Love", "artist": "Pop Smoke"},
    {"title": "Invincible", "artist": "Pop Smoke"},
    {"title": "Mood", "artist": "Pop Smoke"},
    {"title": "Welcome to the Party", "artist": "Pop Smoke"},
    {"title": "BACKGROUND", "artist": "Playboy Carti"},
    {"title": "Magnolia", "artist": "Playboi Carti"},
    {"title": "shoota", "artist": "Playboi Carti"},
    {"title": "Sky", "artist": "Playboi Carti"},
    {"title": "wokeuplikethis", "artist": "Playboi Carti"},
    {"title": "Praise The Lord", "artist": "A$AP Rocky"},
    {"title": "Sundress", "artist": "A$AP Rocky"},
    {"title": "L$D", "artist": "A$AP Rocky"},
    {"title": "Fashion Killa", "artist": "A$AP Rocky"},
    {"title": "Trance", "artist": "Metro Boomin"},
    {"title": "Creepin", "artist": "Metro Boomin"},
    {"title": "Around Me", "artist": "Metro Boomin"},
    {"title": "Self Love", "artist": "Metro Boomin"},
    # Drill / UK
    {"title": "Body", "artist": "Tion Wayne"},
    {"title": "Kenji", "artist": "Lil Uzi Vert"},
    {"title": "Plugged In", "artist": "Fumez The Engineer"},
    {"title": "Inferno", "artist": "Sub Urban"},
    {"title": "EDAMAME", "artist": "bbno$"},
    {"title": "Lalala", "artist": "Y2K"},
    # Electronic / EDM
    {"title": "Faded", "artist": "Alan Walker"},
    {"title": "Darkside", "artist": "Alan Walker"},
    {"title": "Alone", "artist": "Alan Walker"},
    {"title": "Spectre", "artist": "Alan Walker"},
    {"title": "The Spectre", "artist": "Alan Walker"},
    {"title": "Play", "artist": "Alan Walker"},
    {"title": "Monody", "artist": "TheFatRat"},
    {"title": "Unity", "artist": "TheFatRat"},
    {"title": "Fly Away", "artist": "TheFatRat"},
    {"title": "Xenogenesis", "artist": "TheFatRat"},
    {"title": "Heroes Tonight", "artist": "Janji"},
    {"title": "NCS Release", "artist": "Tobu"},
    {"title": "Candyland", "artist": "Tobu"},
    {"title": "Cloud 9", "artist": "Tobu"},
    {"title": "Levan Polka", "artist": "Bilal Göregen"},
    {"title": "Astronomia", "artist": "Vicetone"},
    # More viral TikTok sounds
    {"title": "Luther", "artist": "Kendrick Lamar"},
    {"title": "Carnival", "artist": "Kanye West"},
    {"title": "Bound 2", "artist": "Kanye West"},
    {"title": "Runaway", "artist": "Kanye West"},
    {"title": "Stronger", "artist": "Kanye West"},
    {"title": "POWER", "artist": "Kanye West"},
    {"title": "Heartless", "artist": "Kanye West"},
    {"title": "All of the Lights", "artist": "Kanye West"},
    {"title": "N****s in Paris", "artist": "Jay-Z & Kanye West"},
    {"title": "In Da Club", "artist": "50 Cent"},
    {"title": "Many Men", "artist": "50 Cent"},
    {"title": "Lose Yourself", "artist": "Eminem"},
    {"title": "Without Me", "artist": "Eminem"},
    {"title": "The Real Slim Shady", "artist": "Eminem"},
    {"title": "Godzilla", "artist": "Eminem"},
    {"title": "Rap God", "artist": "Eminem"},
    {"title": "Till I Collapse", "artist": "Eminem"},
    {"title": "Mockingbird", "artist": "Eminem"},
    # R&B / Chill
    {"title": "After Hours", "artist": "The Weeknd"},
    {"title": "Often", "artist": "The Weeknd"},
    {"title": "Call Out My Name", "artist": "The Weeknd"},
    {"title": "Earned It", "artist": "The Weeknd"},
    {"title": "I Feel It Coming", "artist": "The Weeknd"},
    {"title": "Moth To A Flame", "artist": "The Weeknd"},
    {"title": "Less Than Zero", "artist": "The Weeknd"},
    {"title": "Take My Breath", "artist": "The Weeknd"},
    {"title": "Sacrifice", "artist": "The Weeknd"},
    # Sport motivation
    {"title": "Unstoppable", "artist": "Sia"},
    {"title": "Hall of Fame", "artist": "The Script"},
    {"title": "Remember The Name", "artist": "Fort Minor"},
    {"title": "Stronger", "artist": "Kelly Clarkson"},
    {"title": "Eye of the Tiger", "artist": "Survivor"},
    {"title": "Centuries", "artist": "Fall Out Boy"},
    {"title": "Thunder", "artist": "Imagine Dragons"},
    {"title": "Warriors", "artist": "Imagine Dragons"},
    {"title": "Whatever It Takes", "artist": "Imagine Dragons"},
    {"title": "Natural", "artist": "Imagine Dragons"},
    {"title": "Radioactive", "artist": "Imagine Dragons"},
    {"title": "Demons", "artist": "Imagine Dragons"},
    {"title": "Bad Liar", "artist": "Imagine Dragons"},
    {"title": "Born For This", "artist": "The Score"},
    {"title": "Legend", "artist": "The Score"},
    {"title": "Victorious", "artist": "Panic! At The Disco"},
    {"title": "Courtesy Call", "artist": "Thousand Foot Krutch"},
    {"title": "Can't Hold Us", "artist": "Macklemore"},
    {"title": "Champion", "artist": "Fall Out Boy"},
    {"title": "Flames", "artist": "David Guetta"},
    {"title": "Titanium", "artist": "David Guetta"},
    # Latin / Reggaeton
    {"title": "Pepas", "artist": "Farruko"},
    {"title": "Tusa", "artist": "Karol G"},
    {"title": "Dákiti", "artist": "Bad Bunny"},
    {"title": "Yonaguni", "artist": "Bad Bunny"},
    {"title": "Ojitos Lindos", "artist": "Bad Bunny"},
    {"title": "Efecto", "artist": "Bad Bunny"},
    {"title": "Me Porto Bonito", "artist": "Bad Bunny"},
    {"title": "La Noche de Anoche", "artist": "Bad Bunny"},
    {"title": "Callaita", "artist": "Bad Bunny"},
    {"title": "Monaco", "artist": "Bad Bunny"},
    # More trending
    {"title": "Daylight", "artist": "David Kushner"},
    {"title": "Escapism", "artist": "RAYE"},
    {"title": "Paint The Town Red", "artist": "Doja Cat"},
    {"title": "Vampire", "artist": "Olivia Rodrigo"},
    {"title": "good 4 u", "artist": "Olivia Rodrigo"},
    {"title": "drivers license", "artist": "Olivia Rodrigo"},
    {"title": "Cruel Summer", "artist": "Taylor Swift"},
    {"title": "Anti-Hero", "artist": "Taylor Swift"},
    {"title": "Shake It Off", "artist": "Taylor Swift"},
    {"title": "As It Was", "artist": "Harry Styles"},
    {"title": "Watermelon Sugar", "artist": "Harry Styles"},
    {"title": "Greedy", "artist": "Tate McRae"},
    {"title": "You Broke Me First", "artist": "Tate McRae"},
    {"title": "Flowers", "artist": "Miley Cyrus"},
    {"title": "River", "artist": "Miley Cyrus"},
    {"title": "Unholy", "artist": "Sam Smith"},
    {"title": "Stay", "artist": "The Kid LAROI"},
    {"title": "Without You", "artist": "The Kid LAROI"},
    {"title": "STAY", "artist": "Justin Bieber"},
    {"title": "Peaches", "artist": "Justin Bieber"},
    {"title": "Die Young", "artist": "Sleepy Hallow"},
    {"title": "Deep End", "artist": "Sleepy Hallow"},
    {"title": "2055", "artist": "Sleepy Hallow"},
]


def get_seed_songs() -> list[dict]:
    """Return the curated seed list with source metadata."""
    return [
        {
            "title": s["title"],
            "artist": s["artist"],
            "source": "seed",
        }
        for s in SEED_SONGS
    ]
